version: '3.4'

services:
  php:
    build: .
    container_name: php
    volumes:
      - .:/usr/src/myapp
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: mysql
    container_name: db
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=tzp
    networks:
      - app-network

networks:
  app-network:
    driver: bridge